import { Transaction, Category } from './types';

export const categories: Category[] = [
  { name: 'Food', icon: '🍔', type: 'expense' },
  { name: 'Transport', icon: '🚇', type: 'expense' },
  { name: 'Home', icon: '🏠', type: 'expense' },
  { name: 'Shopping', icon: '🛍️', type: 'expense' },
  { name: 'Leisure', icon: '🎬', type: 'expense' },
  { name: 'Health', icon: '💊', type: 'expense' },
  { name: 'Education', icon: '📚', type: 'expense' },
  { name: 'Utilities', icon: '💡', type: 'expense' },
  { name: 'Other', icon: '📦', type: 'expense' },
  { name: 'Salary', icon: '💰', type: 'income' },
  { name: 'Freelance', icon: '💻', type: 'income' },
  { name: 'Investment', icon: '📈', type: 'income' },
  { name: 'Gift', icon: '🎁', type: 'income' },
  { name: 'Other Income', icon: '💵', type: 'income' },
];

export const sampleTransactions: Transaction[] = [
  {
    id: '1',
    date: '2026-09-25',
    title: 'Lunch',
    category: 'Food',
    type: 'expense',
    amount: 38.00,
    icon: '🍔',
  },
  {
    id: '2',
    date: '2026-09-24',
    title: 'Metro commute',
    category: 'Transport',
    type: 'expense',
    amount: 16.00,
    icon: '🚇',
  },
  {
    id: '3',
    date: '2026-09-23',
    title: 'Monthly salary',
    category: 'Salary',
    type: 'income',
    amount: 12800.00,
    icon: '💰',
  },
  {
    id: '4',
    date: '2026-09-22',
    title: 'Rent',
    category: 'Home',
    type: 'expense',
    amount: 3200.00,
    icon: '🏠',
  },
  {
    id: '5',
    date: '2026-09-21',
    title: 'Household items',
    category: 'Shopping',
    type: 'expense',
    amount: 129.00,
    icon: '🛍️',
  },
  {
    id: '6',
    date: '2026-09-20',
    title: 'Coffee and pastry',
    category: 'Food',
    type: 'expense',
    amount: 45.00,
    icon: '🍔',
  },
  {
    id: '7',
    date: '2026-09-18',
    title: 'Project payment',
    category: 'Freelance',
    type: 'income',
    amount: 680.00,
    icon: '💻',
  },
  {
    id: '8',
    date: '2026-09-17',
    title: 'Movie ticket',
    category: 'Leisure',
    type: 'expense',
    amount: 78.00,
    icon: '🎬',
  },
  {
    id: '9',
    date: '2026-09-15',
    title: 'Dinner',
    category: 'Food',
    type: 'expense',
    amount: 56.00,
    icon: '🍔',
  },
];
